Added test_user_stake

diff --git a/test/common b/test/common
--- a/test/common
+++ b/test/common
@@ -157,8 +157,10 @@ function assert_fail ()
                 fi
                 sleep 1
             done
-            echo "FAIL: $TEST_NAME did not land"
-            exit 1
+            if [ -z "$TEST_OUTPUT" ]; then
+                echo "FAIL: $TEST_NAME did not land ($SIGNATURE)"
+                exit 1
+            fi
         fi
     fi
 
@@ -216,17 +218,11 @@ function make_stake_account ()
     local STAKE_KEY_FILE=$2
     local SOL=$3
 
-    if [ -n "$4" ]; then
-        local COMMITMENT="--commitment finalized"
-    else
-        local COMMITMENT=
-    fi
-    
     echo "Creating stake account @ $STAKE_KEY_FILE authority $AUTHORITY_KEY_FILE with lamports $SOL"
 
     solana-keygen new -o $STAKE_KEY_FILE --no-bip39-passphrase --force >/dev/null 2>/dev/null
 
-    solana -u l create-stake-account -k $AUTHORITY_KEY_FILE $STAKE_KEY_FILE $SOL $COMMITMENT >/dev/null 2>/dev/null
+    solana -u l create-stake-account -k $AUTHORITY_KEY_FILE $STAKE_KEY_FILE $SOL $4 >/dev/null 2>/dev/null
 }
 
 
@@ -326,57 +322,56 @@ function sleep_until_next_epoch ()
 
 function setup ()
 {
-    # Make a temporary directory to hold the validator ledger
-    export LEDGER=`mktemp -d`
-
-    echo "Starting test validator @ $LEDGER"
-    
-    solana-test-validator --ledger $LEDGER --ticks-per-slot 16 --slots-per-epoch 100                                  \
-                          -u https://api.mainnet-beta.solana.com -c metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s       \
-                          -c PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT >/dev/null 2>/dev/null &
-
-    echo "Waiting 5 seconds for it to settle"
-
-    # Give it time to start
-    sleep 5
-
-    # Detect the vote account
-    export VALIDATOR_PUBKEY=`solana -u http://localhost:8899 validators 2>/dev/null | head -2 | tail -1               \
-                             | awk '{ print $2 }'`
-    export VOTE_PUBKEY=`solana -u http://localhost:8899 validators 2>/dev/null | head -2 | tail -1                    \
-                        | awk '{ print $3 }'`
-
-    # Create keys: program, super, admin, rich_user1, rich_user2, poor_user, nonexistent_user
-    make_funded_keypair $LEDGER/program.json 0
-    make_funded_keypair $LEDGER/super.json 100000
-    make_funded_keypair $LEDGER/admin.json 100000
-    make_funded_keypair $LEDGER/rich_user1.json 100000
-    make_funded_keypair $LEDGER/rich_user2.json 100000
-    make_funded_keypair $LEDGER/poor_user.json 0.01
-    make_funded_keypair $LEDGER/nonexistent_user.json 0 finalized
-
-    # Build the program
-    echo "Making build script"
-    $SOURCE/make_build_program.sh $LEDGER/program.json $LEDGER/super.json $VOTE_PUBKEY > $LEDGER/build_program.sh
-    chmod +x $LEDGER/build_program.sh
-    echo "Building program"
-    (cd $LEDGER; SDK_ROOT=~/.local/share/solana/install/active_release/bin/sdk SOURCE_ROOT=$SOURCE ./build_program.sh)
-
-    # Create stake accounts: delegated_stake, undelegated_stake
-    make_stake_account $LEDGER/rich_user1.json $LEDGER/delegated_stake.json 1000
-    make_stake_account $LEDGER/rich_user1.json $LEDGER/undelegated_stake.json 1000 finalized
-
-    # Delegate the delegated stake account
-    echo "Delegating $LEDGER/delegated_stake.json"
-    solana -u l delegate-stake -k $LEDGER/rich_user1.json $LEDGER/delegated_stake.json $VOTE_PUBKEY                    \
-           >/dev/null 2>/dev/null
-
-    # Deploy the program
-    echo "Deploying program"
-    solana -k $LEDGER/super.json -u l program deploy --program-id $LEDGER/program.json $LEDGER/program.so              \
-           --commitment finalized >/dev/null 2>/dev/null
-
-#    export LEDGER=/tmp/tmp.nMGEqfdOYe
+    if [ -z "$TEST_NO_SETUP" ]; then
+        # Make a temporary directory to hold the validator ledger
+        export LEDGER=`mktemp -d`
+        
+        echo "Starting test validator @ $LEDGER"
+        
+        # Start the test validator
+        solana-test-validator --ledger $LEDGER --ticks-per-slot 16 --slots-per-epoch 100                               \
+                              -u https://api.mainnet-beta.solana.com -c metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s    \
+                              -c PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT >/dev/null 2>/dev/null &
+        
+        echo "Waiting 5 seconds for it to settle"
+        
+        # Give it time to start
+        sleep 5
+        
+        # Detect the vote account
+        export VALIDATOR_PUBKEY=`solana -u http://localhost:8899 validators 2>/dev/null | head -2 | tail -1            \
+                                                     | awk '{ print $2 }'`
+        export VOTE_PUBKEY=`solana -u http://localhost:8899 validators 2>/dev/null | head -2 | tail -1                 \
+                        | awk '{ print $3 }'                `
+        
+        # Create keys: program, super, admin, rich_user1, rich_user2, poor_user, nonexistent_user
+        make_funded_keypair $LEDGER/program.json 0
+        make_funded_keypair $LEDGER/super.json 100000
+        make_funded_keypair $LEDGER/admin.json 100000
+        make_funded_keypair $LEDGER/rich_user1.json 100000
+        make_funded_keypair $LEDGER/rich_user2.json 100000
+        make_funded_keypair $LEDGER/poor_user.json 0.01
+        make_funded_keypair $LEDGER/nonexistent_user.json 0 finalized
+        
+        # Build the program
+        echo "Making build script"
+        $SOURCE/make_build_program.sh $LEDGER/program.json $LEDGER/super.json $VOTE_PUBKEY > $LEDGER/build_program.sh
+        chmod +x $LEDGER/build_program.sh
+        echo "Building program"
+        (cd $LEDGER;                                                                                                   \
+         SDK_ROOT=~/.local/share/solana/install/active_release/bin/sdk SOURCE_ROOT=$SOURCE ./build_program.sh)
+        
+        # Deploy the program.
+        echo "Deploying program"
+        solana -k $LEDGER/super.json -u l program deploy --program-id $LEDGER/program.json $LEDGER/program.so          \
+               --commitment finalized >/dev/null 2>/dev/null
+    else
+        export VALIDATOR_PUBKEY=`solana -u http://localhost:8899 validators 2>/dev/null | head -2 | tail -1            \
+                                     | awk '{ print $2 }'`
+        export VOTE_PUBKEY=`solana -u http://localhost:8899 validators 2>/dev/null | head -2 | tail -1                 \
+                            | awk '{ print $3 }'`
+        export LEDGER=/tmp/tmp.*
+    fi
     
 # Compute pubkeys
 
@@ -387,8 +382,6 @@ function setup ()
     export           RICH_USER2_PUBKEY=`solpda -pubkey $LEDGER/rich_user2.json`
     export            POOR_USER_PUBKEY=`solpda -pubkey $LEDGER/poor_user.json`
     export     NONEXISTENT_USER_PUBKEY=`solpda -pubkey $LEDGER/nonexistent_user.json`
-    export      DELEGATED_STAKE_PUBKEY=`solpda -pubkey $LEDGER/delegated_stake.json`
-    export    UNDELEGATED_STAKE_PUBKEY=`solpda -pubkey $LEDGER/undelegated_stake.json`
     export       SYSTEM_PROGRAM_PUBKEY=`echo 11111111111111111111111111111111`
     export    SPL_TOKEN_PROGRAM_PUBKEY=`echo TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`
     export       SPLATA_PROGRAM_PUBKEY=`echo ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL`
